<?php
/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
include_once $GLOBALS['THRIFT_ROOT'].'/packages/Types/Types_types.php';

$GLOBALS['Types_CONSTANTS'] = array();

$GLOBALS['Types_CONSTANTS']['EDAM_NOTE_SOURCE_WEB_CLIP'] = "web.clip";

$GLOBALS['Types_CONSTANTS']['EDAM_NOTE_SOURCE_MAIL_CLIP'] = "mail.clip";

$GLOBALS['Types_CONSTANTS']['EDAM_NOTE_SOURCE_MAIL_SMTP_GATEWAY'] = "mail.smtp";

?>
