<?php
/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
include_once $GLOBALS['THRIFT_ROOT'].'/packages/UserStore/UserStore_types.php';

$GLOBALS['UserStore_CONSTANTS'] = array();

$GLOBALS['UserStore_CONSTANTS']['EDAM_VERSION_MAJOR'] = 1;

$GLOBALS['UserStore_CONSTANTS']['EDAM_VERSION_MINOR'] = 17;

?>
